language: java
jdk: openjdk17

services:
  - docker

before_install:
  - git branch -a
  - git checkout origin/master
  - chmod +x gradlew

script:
  - ./gradlew clean build

after_success:
  - docker-compose up -d --build

after_script:
  - docker-compose down

notifications:
  email: yonathanw@outlook.es
